# jwt configuration
jwt:
  signing-key: 'wa1kman'
  expires-time: 604800
  buffer-time: 86400
  issuer: 'wa1kman'

## zap logger configuration
#zap:
#  level: 'info'
#  format: 'console'
#  prefix: '[GoBlog]'
#  director: 'log'
#  show-line: true
#  encode-level: 'LowercaseColorLevelEncoder'
#  stacktrace-key: 'stacktrace'
#  log-in-console: true

# redis configuration
redis:
  db: 0
  addr: '127.0.0.1:6379'
  password: ''

# system configuration
system:
  env: 'public'  # Change to "develop" to skip authentication for development mode
  host: '127.0.0.1'
  port: '8081'
  db-type: 'mysql'
  oss-type: 'local'    # 控制oss选择走本期还是 七牛等其他仓 自行增加其他oss仓可以在 server/utils/upload/upload.go 中 NewOss函数配置
  use-multipoint: false
  # IP限制次数 一个小时15000次
  iplimit-count: 15000
  #  IP限制一个小时
  iplimit-time: 3600

# mysql connect configuration
mysql:
  path: '127.0.0.1'
  port: '3306'
  config: 'parseTime=true'
  db-name: 'goblog'
  username: 'root'
  password: 'root'
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: "Silent"
  log-zap: false